SERVERS = ['us-aegwynn', 'us-aerie-peak', 'us-agamaggan', 'us-aggramar', 'us-akama', 'us-alexstrasza', 'us-alleria',
           'us-altar-of-storms', 'us-alterac-mountains', 'us-amanthul', 'us-andorhal', 'us-anetheron', 'us-antonidas',
           'us-anubarak', 'us-anvilmar', 'us-arathor', 'us-archimonde', 'us-area-52', 'us-argent-dawn', 'us-arthas',
           'us-arygos', 'us-auchindoun', 'us-azgalor', 'us-azjol-nerub', 'us-azralon', 'us-azshara', 'us-azuremyst',
           'us-baelgun', 'us-balnazzar', 'us-barthilas', 'us-black-dragonflight', 'us-blackhand', 'us-blackrock',
           'us-blackwater-raiders', 'us-blackwing-lair', 'us-blades-edge', 'us-bladefist', 'us-bleeding-hollow',
           'us-blood-furnace', 'us-bloodhoof', 'us-bloodscalp', 'us-bonechewer', 'us-borean-tundra', 'us-boulderfist',
           'us-bronzebeard', 'us-burning-blade', 'us-burning-legion', 'us-caelestrasz', 'us-cairne',
           'us-cenarion-circle', 'us-cenarius', 'us-chogall', 'us-chromaggus', 'us-coilfang', 'us-crushridge',
           'us-daggerspine', 'us-dalaran', 'us-dalvengyr', 'us-dark-iron', 'us-darkspear', 'us-darrowmere',
           'us-dathremar', 'us-dawnbringer', 'us-deathwing', 'us-demon-soul', 'us-dentarg', 'us-destromath',
           'us-dethecus', 'us-detheroc', 'us-doomhammer', 'us-draenor', 'us-dragonblight', 'us-dragonmaw',
           'us-draktharon', 'us-drakthul', 'us-draka', 'us-drakkari', 'us-dreadmaul', 'us-drenden', 'us-dunemaul',
           'us-durotan', 'us-duskwood', 'us-earthen-ring', 'us-echo-isles', 'us-eitrigg', 'us-eldrethalas', 'us-elune',
           'us-emerald-dream', 'us-eonar', 'us-eredar', 'us-executus', 'us-exodar', 'us-farstriders', 'us-feathermoon',
           'us-fenris', 'us-firetree', 'us-fizzcrank', 'us-frostmane', 'us-frostmourne', 'us-frostwolf', 'us-galakrond',
           'us-gallywix', 'us-garithos', 'us-garona', 'us-garrosh', 'us-ghostlands', 'us-gilneas', 'us-gnomeregan',
           'us-goldrinn', 'us-gorefiend', 'us-gorgonnash', 'us-greymane', 'us-grizzly-hills', 'us-guldan', 'us-gundrak',
           'us-gurubashi', 'us-hakkar', 'us-haomarush', 'us-hellscream', 'us-hydraxis', 'us-hyjal', 'us-icecrown',
           'us-illidan', 'us-jaedenar', 'us-jubeithos', 'us-kaelthas', 'us-kalecgos', 'us-kargath', 'us-kelthuzad',
           'us-khadgar', 'us-khaz-modan', 'us-khazgoroth', 'us-kiljaeden', 'us-kilrogg', 'us-kirin-tor', 'us-korgath',
           'us-korialstrasz', 'us-kul-tiras', 'us-laughing-skull', 'us-lethon', 'us-lightbringer',
           'us-lightnings-blade', 'us-lightninghoof', 'us-llane', 'us-lothar', 'us-madoran', 'us-maelstrom',
           'us-magtheridon', 'us-maiev', 'us-malganis', 'us-malfurion', 'us-malorne', 'us-malygos', 'us-mannoroth',
           'us-medivh', 'us-misha', 'us-moknathal', 'us-moon-guard', 'us-moonrunner', 'us-mugthol', 'us-muradin',
           'us-nagrand', 'us-nathrezim', 'us-nazgrel', 'us-nazjatar', 'us-nemesis', 'us-nerzhul', 'us-nesingwary',
           'us-nordrassil', 'us-norgannon', 'us-onyxia', 'us-perenolde', 'us-proudmoore', 'us-quelthalas',
           'us-queldorei', 'us-ragnaros', 'us-ravencrest', 'us-ravenholdt', 'us-rexxar', 'us-rivendare', 'us-runetotem',
           'us-sargeras', 'us-saurfang', 'us-scarlet-crusade', 'us-scilla', 'us-senjin', 'us-sentinels',
           'us-shadow-council', 'us-shadowmoon', 'us-shadowsong', 'us-shandris', 'us-shattered-halls',
           'us-shattered-hand', 'us-shuhalo', 'us-silver-hand', 'us-silvermoon', 'us-sisters-of-elune',
           'us-skullcrusher', 'us-skywall', 'us-smolderthorn', 'us-spinebreaker', 'us-spirestone', 'us-staghelm',
           'us-steamwheedle-cartel', 'us-stonemaul', 'us-stormrage', 'us-stormreaver', 'us-stormscale', 'us-suramar',
           'us-tanaris', 'us-terenas', 'us-terokkar', 'us-thaurissan', 'us-the-forgotten-coast', 'us-the-scryers',
           'us-the-underbog', 'us-the-venture-co', 'us-thorium-brotherhood', 'us-thrall', 'us-thunderhorn',
           'us-thunderlord', 'us-tichondrius', 'us-tol-barad', 'us-tortheldrin', 'us-trollbane', 'us-turalyon',
           'us-twisting-nether', 'us-uldaman', 'us-uldum', 'us-undermine', 'us-ursin', 'us-uther', 'us-vashj',
           'us-veknilash', 'us-velen', 'us-warsong', 'us-whisperwind', 'us-wildhammer', 'us-windrunner',
           'us-winterhoof', 'us-wyrmrest-accord', 'us-ysera', 'us-ysondre', 'us-zangarmarsh', 'us-zuljin', 'us-zuluhed']
